from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[("api","0009_pricing"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name="Notification",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("role",models.CharField(blank=True,max_length=20)),("title",models.CharField(max_length=140)),("message",models.CharField(max_length=300)),("read",models.BooleanField(default=False)),("created_at",models.DateTimeField(auto_now_add=True)),("user",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name="partora_notifications",to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="ApprovalRequest",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("kind",models.CharField(choices=[("purchase","Purchase"),("discount","Discount"),("stock","Stock adjustment")],max_length=20)),("reference",models.CharField(max_length=80)),("amount",models.DecimalField(decimal_places=2,default=0,max_digits=14)),("status",models.CharField(choices=[("pending","Pending"),("approved","Approved"),("rejected","Rejected")],default="pending",max_length=20)),("notes",models.CharField(blank=True,max_length=300)),("created_at",models.DateTimeField(auto_now_add=True)),("reviewed_at",models.DateTimeField(blank=True,null=True)),("requested_by",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="approval_requests",to=settings.AUTH_USER_MODEL)),("reviewed_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="approval_reviews",to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="AuditLog",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("action",models.CharField(max_length=80)),("entity",models.CharField(max_length=80)),("entity_id",models.CharField(blank=True,max_length=80)),("detail",models.CharField(blank=True,max_length=300)),("created_at",models.DateTimeField(auto_now_add=True)),("user",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="partora_audit_logs",to=settings.AUTH_USER_MODEL))])]
