# Generated by Django 5.2.17 on 2026-09-23 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_goodsreceipt_goodsreceiptline_supplierinvoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_no", models.CharField(max_length=40, unique=True)),
                ("expires_on", models.DateField()),
                ("payment_terms", models.CharField(blank=True, max_length=80)),
                (
                    "annual_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expiring", "Expiring soon"),
                            ("review", "Needs review"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="api.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["expires_on", "supplier__name"],
            },
        ),
    ]
