# Generated by Django 5.2.17 on 2026-09-25 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_suppliercontract"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FleetVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration", models.CharField(max_length=30, unique=True)),
                ("customer", models.CharField(max_length=140)),
                ("make", models.CharField(max_length=80)),
                ("model", models.CharField(max_length=80)),
                ("year", models.PositiveIntegerField(default=2022)),
                ("mileage", models.PositiveIntegerField(default=0)),
                ("next_service", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("due_soon", "Due soon"),
                            ("overdue", "Overdue"),
                        ],
                        default="healthy",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("trigger", models.CharField(max_length=120)),
                ("action", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("paused", "Paused")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("runs", models.PositiveIntegerField(default=0)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AutomationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.CharField(default="success", max_length=20)),
                ("detail", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_history",
                        to="api.automationrule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_no", models.CharField(max_length=40, unique=True)),
                ("driver", models.CharField(max_length=120)),
                ("vehicle", models.CharField(max_length=80)),
                ("stops", models.PositiveIntegerField(default=1)),
                ("completed", models.PositiveIntegerField(default=0)),
                ("eta", models.CharField(blank=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_transit", "In transit"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FleetWorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_no", models.CharField(max_length=40, unique=True)),
                ("registration", models.CharField(max_length=30)),
                ("customer", models.CharField(max_length=140)),
                ("technician", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "parts_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "labor_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fleet_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="api.fleetvehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("accounting", "Accounting"),
                            ("messaging", "Messaging"),
                            ("shipping", "Shipping"),
                            ("payments", "Payments"),
                            ("webhook", "Webhook"),
                        ],
                        default="webhook",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("attention", "Needs attention"),
                            ("available", "Available"),
                            ("disabled", "Disabled"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("records", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integration_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=120)),
                ("target", models.CharField(blank=True, max_length=300)),
                ("status", models.CharField(default="delivered", max_length=20)),
                ("detail", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="api.integrationconnection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PwaDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("blocked", "Blocked"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("app_version", models.CharField(blank=True, max_length=30)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pwa_devices",
                        to="api.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipment_no", models.CharField(max_length=40, unique=True)),
                ("customer", models.CharField(max_length=140)),
                ("order_no", models.CharField(blank=True, max_length=40)),
                ("driver", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_transit", "In transit"),
                            ("delivered", "Delivered"),
                            ("exception", "Exception"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("eta", models.DateTimeField(blank=True, null=True)),
                (
                    "pod_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("verified", "Verified")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("proof_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments",
                        to="api.deliveryroute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_no", models.CharField(max_length=40, unique=True)),
                ("customer", models.CharField(max_length=140)),
                ("subject", models.CharField(max_length=200)),
                ("channel", models.CharField(default="portal", max_length=40)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("pending_customer", "Pending customer"),
                            ("escalated", "Escalated"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("assignee", models.CharField(blank=True, max_length=120)),
                ("sla_due", models.DateTimeField(blank=True, null=True)),
                ("last_message", models.CharField(blank=True, max_length=300)),
                ("messages", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupportCommunication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor", models.CharField(max_length=120)),
                ("channel", models.CharField(max_length=40)),
                ("message", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="api.supportticket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=80)),
                ("field", models.CharField(max_length=80)),
                ("local_value", models.CharField(max_length=240)),
                ("server_value", models.CharField(max_length=240)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("needs_review", "Needs review"),
                            ("resolved", "Resolved"),
                        ],
                        default="needs_review",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="api.pwadevice",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_sync_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebhookSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=100)),
                ("target", models.URLField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deliveries", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="api.integrationconnection",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
