# Generated by Django 5.2.17 on 2026-09-25 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_organization_automationrule_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationrun",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automationrun_records",
                to="api.organization",
            ),
        ),
    ]
