# Generated by Django 5.2.17 on 2026-09-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_portalaccesslog"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="api_product_name_73c704_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["brand", "category"], name="api_product_brand_4ce2df_idx"
            ),
        ),
    ]
