# Generated by Django 5.2.17 on 2026-09-25 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_purchaseorderstatusevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationconnection",
            name="credential_digest",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="integrationconnection",
            name="failure_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="integrationconnection",
            name="last_error",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="webhooksubscription",
            name="signing_key_digest",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=100)),
                ("payload", models.TextField(default="{}")),
                ("signature", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("delivered", "Delivered"),
                            ("retrying", "Retrying"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhookdelivery_records",
                        to="api.organization",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempts",
                        to="api.webhooksubscription",
                    ),
                ),
            ],
        ),
    ]
