# Generated by Django 5.2.17 on 2026-09-25 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_integrationconnection_credential_digest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pwadevice",
            name="device_key",
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="pwadevice",
            name="sync_cursor",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="MobileTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_type", models.CharField(max_length=30)),
                ("reference", models.CharField(max_length=80)),
                ("location", models.CharField(blank=True, max_length=80)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("synced", "Synced"),
                            ("complete", "Complete"),
                            ("conflict", "Conflict"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=120, unique=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="api.pwadevice",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobiletask_records",
                        to="api.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mobile_tasks",
                        to="api.product",
                    ),
                ),
            ],
        ),
    ]
