# Generated by Django 5.2.17 on 2026-09-25 06:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_pwadevice_device_key_pwadevice_sync_cursor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
        migrations.CreateModel(
            name="FinanceTaxRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=18, max_digits=5),
                ),
                (
                    "effective_from",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financetaxrule_records",
                        to="api.organization",
                    ),
                ),
            ],
        ),
    ]
