# Generated by Django 5.2.17 on 2026-09-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_invoice_tax_rate_financetaxrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("sales", "Sales"),
                    ("store", "Store"),
                    ("client", "Client"),
                ],
                default="store",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("sales", "Sales"),
                    ("store", "Store"),
                    ("client", "Client"),
                ],
                default="sales",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("sales", "Sales"),
                    ("store", "Store"),
                    ("client", "Client"),
                ],
                default="sales",
                max_length=20,
            ),
        ),
    ]
