# Generated by Django 5.2.17 on 2026-09-25 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_permissions(apps, schema_editor):
    PermissionDefinition = apps.get_model("api", "PermissionDefinition")
    RolePermission = apps.get_model("api", "RolePermission")
    actions = [("view", "View"), ("create", "Create"), ("edit", "Edit"), ("approve", "Approve"), ("export", "Export")]
    role_modules = {
        "admin": {"dashboard", "inventory", "quotations", "suppliers", "stock", "barcodes", "fitments", "purchase_orders", "receiving", "mobile_warehouse", "warehouses", "reorder", "demand_planning", "rfq", "sales_flow", "fulfillment", "notifications", "copilot", "finance", "warranty_intelligence", "integrations", "pwa_admin", "tenancy", "automation", "fleet", "security", "documents", "delivery", "partner_api", "predictive_fleet", "customer_service", "saas_billing", "observability", "inventory_network", "returns", "inventory_control", "supplier_performance", "portal", "crm", "pricing", "analytics", "governance"},
        "manager": {"dashboard", "inventory", "quotations", "suppliers", "stock", "barcodes", "fitments", "purchase_orders", "receiving", "mobile_warehouse", "warehouses", "reorder", "demand_planning", "rfq", "sales_flow", "fulfillment", "notifications", "copilot", "finance", "warranty_intelligence", "integrations", "tenancy", "automation", "fleet", "delivery", "customer_service", "inventory_network", "returns", "inventory_control", "supplier_performance", "portal", "crm", "pricing", "analytics", "governance"},
        "sales": {"dashboard", "inventory", "quotations", "barcodes", "fitments", "sales_flow", "fulfillment", "notifications", "copilot", "customer_service", "portal", "crm", "pricing", "analytics"},
        "store": {"dashboard", "inventory", "stock", "barcodes", "fitments", "purchase_orders", "receiving", "mobile_warehouse", "warehouses", "reorder", "fulfillment", "notifications", "returns", "inventory_control"},
    }
    for role, modules in role_modules.items():
        for module in modules:
            for action, label in actions:
                permission, _ = PermissionDefinition.objects.get_or_create(module=module, action=action, defaults={"label": f"{label} {module.replace('_', ' ').title()}"})
                allowed = role == "admin" or action == "view" or (action in {"create", "edit"} and role in {"manager", "sales", "store"}) or (action in {"approve", "export"} and role == "manager")
                RolePermission.objects.get_or_create(role=role, permission=permission, defaults={"allowed": allowed})


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_alter_organizationinvitation_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=60)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("create", "Create"),
                            ("edit", "Edit"),
                            ("approve", "Approve"),
                            ("export", "Export"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["module", "action"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("module", "action"), name="unique_permission_definition"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("sales", "Sales"),
                            ("store", "Store"),
                        ],
                        max_length=20,
                    ),
                ),
                ("allowed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_grants",
                        to="api.permissiondefinition",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("role", "permission"), name="unique_role_permission"
                    )
                ],
            },
        ),
        migrations.RunPython(seed_permissions, migrations.RunPython.noop),
    ]
