# Generated by Django 5.2.17 on 2026-09-25 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_permissiondefinition_rolepermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmembership",
            name="all_branches",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="primary_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member_scopes",
                to="api.warehouse",
            ),
        ),
    ]
