# Generated by Django 5.2.17 on 2026-09-25 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_organizationmembership_all_branches_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrequest",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_requests",
                to="api.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_requests",
                to="api.organization",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("discount", "Discount"),
                    ("stock", "Stock adjustment"),
                    ("payment", "Payment"),
                ],
                max_length=20,
            ),
        ),
    ]
