from django.urls import path
from . import views

urlpatterns = [
    path("health/", views.health),
    path("auth/login/", views.login_view),
    path("auth/me/", views.me_view),
    path("dashboard/", views.dashboard_view),
    path("inventory/", views.inventory_view),
    path("suppliers/", views.suppliers_view),
    path("quotations/", views.quotations_view),
    path("stock/", views.stock_view),
    path("barcodes/", views.barcodes_view),
    path("barcodes/lookup/", views.barcode_lookup_view),
    path("fitments/", views.fitments_view),
    path("purchase-orders/", views.purchase_orders_view),
    path("receiving/", views.receiving_view),
    path("mobile-warehouse/", views.mobile_warehouse_view),
    path("warehouses/", views.warehouses_view),
    path("reorder/", views.reorder_view),
    path("demand-planning/", views.demand_planning_view),
    path("rfq/", views.rfq_view),
    path("sales-flow/", views.sales_flow_view),
    path("fulfillment/", views.fulfillment_view),
    path("notifications/", views.notifications_view),
    path("copilot/", views.copilot_view),
    path("finance/", views.finance_view),
    path("warranty/", views.warranty_view),
    path("returns/", views.returns_view),
    path("inventory-control/", views.inventory_control_view),
    path("supplier-performance/", views.supplier_performance_view),
    path("customers/", views.customers_view),
    path("portal/", views.portal_view),
    path("portal/issue/", views.portal_issue_view),
    path("pricing/", views.pricing_view),
    path("analytics/", views.analytics_view),
    path("governance/", views.governance_view),
]
