import { useEffect, useState } from 'react'
import { createEndpoint, loadEndpoint } from '../api/client'
import { useAuth } from '../context/AuthContext'
import CreateModal from '../components/CreateModal'

function OpsHeader({ eyebrow, title, copy, action }) {
  return <header className="app-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{action}</header>
}
function Loading(){ return <div className="loading-card">Loading operational data…</div> }
function ErrorBox({ message }){ return <div className="error-card">{message}</div> }
export function BarcodePage(){
  const { user }=useAuth(); const [items,setItems]=useState([]); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [creating,setCreating]=useState(false); const [q,setQ]=useState('')
  useEffect(()=>{loadEndpoint('/barcodes/',user.role).then(r=>{setItems(r.data.items);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  const filtered=items.filter(x=>!q || [x.sku,x.name,x.barcode].join(' ').toLowerCase().includes(q.toLowerCase()))
  async function assign(form){const r=await createEndpoint('/barcodes/',form,user.role);setItems(curr=>[r.item,...curr.filter(x=>x.id!==r.item.id)])}
  return <><OpsHeader eyebrow="Scan desk" title="Barcode & QR labels" copy="Assign, scan and search part labels from one fast inventory surface." action={<button className="button app-action" onClick={()=>setCreating(true)}>Assign label</button>}/>
    <div className="toolbar"><div className="searchbox">▣<input autoFocus placeholder="Scan barcode, QR value or enter SKU…" value={q} onChange={e=>setQ(e.target.value)}/></div><span>{filtered.length} labelled parts</span></div>
    {loading?<Loading/>:error?<ErrorBox message={error}/>:<div className="table-card"><table><thead><tr><th>Part</th><th>Barcode / QR value</th><th>Stock</th><th>Bin</th><th>Label</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><b>{x.name}</b><small>{x.sku} · {x.brand}</small></td><td><code>{x.barcode || 'Not assigned'}</code></td><td>{x.stock_qty}</td><td>{x.bin_location}</td><td><button className="mini-button" onClick={()=>window.print()}>Print</button></td></tr>)}</tbody></table></div>}
    {creating&&<CreateModal title="Assign barcode" copy="Use an existing barcode/QR value or leave blank to generate an internal Partora code." submitLabel="Assign" onClose={()=>setCreating(false)} onSubmit={assign} fields={[{name:'sku',label:'SKU',required:true},{name:'barcode',label:'Barcode / QR value',placeholder:'8901234567890',span:2}]}/>}</>
}

export function FitmentsPage(){
  const { user }=useAuth(); const [items,setItems]=useState([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [creating,setCreating]=useState(false)
  useEffect(()=>{loadEndpoint('/fitments/',user.role).then(r=>{setItems(r.data.items);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  const filtered=items.filter(x=>!q||[x.make,x.model,x.variant,x.engine,x.oem_number,x.sku,x.product].join(' ').toLowerCase().includes(q.toLowerCase()))
  async function add(form){const r=await createEndpoint('/fitments/',form,user.role);setItems(c=>[r.item,...c])}
  return <><OpsHeader eyebrow="Compatibility" title="Vehicle & part fitment" copy="Find compatible parts by make, model, year, variant, engine or OEM reference." action={<button className="button app-action" onClick={()=>setCreating(true)}>+ Add fitment</button>}/><div className="toolbar"><div className="searchbox">⌕<input placeholder="Swift 2022, i20 1.2L, OEM number…" value={q} onChange={e=>setQ(e.target.value)}/></div><span>{filtered.length} matches</span></div>{loading?<Loading/>:error?<ErrorBox message={error}/>:<div className="table-card"><table><thead><tr><th>Vehicle</th><th>Years</th><th>Variant / Engine</th><th>Part</th><th>OEM</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><b>{x.make} {x.model}</b></td><td>{x.year_from}–{x.year_to}</td><td>{x.variant}<small>{x.engine}</small></td><td><b>{x.product}</b><small>{x.sku}</small></td><td>{x.oem_number||'—'}</td></tr>)}</tbody></table></div>}{creating&&<CreateModal title="Add vehicle fitment" copy="Map a catalog SKU to vehicle compatibility and OEM references." submitLabel="Add fitment" onClose={()=>setCreating(false)} onSubmit={add} fields={[{name:'sku',label:'SKU',required:true},{name:'make',label:'Make',required:true},{name:'model',label:'Model',required:true},{name:'year_from',label:'From year',type:'number',required:true},{name:'year_to',label:'To year',type:'number'},{name:'variant',label:'Variant'},{name:'engine',label:'Engine'},{name:'oem_number',label:'OEM number'}]}/>}</>
}

export function PurchaseOrdersPage(){
  const { user }=useAuth(); const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [creating,setCreating]=useState(false)
  useEffect(()=>{loadEndpoint('/purchase-orders/',user.role).then(r=>{setItems(r.data.items);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  async function add(form){const r=await createEndpoint('/purchase-orders/',form,user.role);setItems(c=>[r.item,...c])}
  async function receive(id){const r=await createEndpoint('/purchase-orders/',{action:'receive',id},user.role);setItems(c=>c.map(x=>x.id===id?{...x,...r.item}:x))}
  return <><OpsHeader eyebrow="Purchasing" title="Purchase orders" copy="Create supplier orders, track expected delivery and receive stock directly into inventory." action={<button className="button app-action" onClick={()=>setCreating(true)}>+ New PO</button>}/>{loading?<Loading/>:error?<ErrorBox message={error}/>:<div className="table-card"><table><thead><tr><th>PO</th><th>Supplier</th><th>Expected</th><th>Total</th><th>Lines received</th><th>Status</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.po_no}</b><small>{x.created_by}</small></td><td>{x.supplier}</td><td>{x.expected_date||'—'}</td><td>₹{Number(x.total||0).toLocaleString('en-IN')}</td><td>{x.received_lines}/{x.line_count}</td><td className="capitalize">{x.status}</td><td>{x.status!=='received'&&<button className="mini-button" onClick={()=>receive(x.id)}>Receive</button>}</td></tr>)}</tbody></table></div>}{creating&&<CreateModal title="New purchase order" copy="Start with one catalog line; additional line-item editing can be layered on this workflow." submitLabel="Create PO" onClose={()=>setCreating(false)} onSubmit={add} initial={{status:'draft',quantity:1}} fields={[{name:'supplier',label:'Supplier',required:true,placeholder:'TorqueLine Components'},{name:'sku',label:'SKU',required:true},{name:'quantity',label:'Quantity',type:'number',required:true,min:'1'},{name:'unit_cost',label:'Unit cost',type:'number',required:true,min:'0',step:'0.01'},{name:'expected_date',label:'Expected date',type:'date'},{name:'status',label:'Status',type:'select',options:['draft','approved','ordered']}]}/>}</>
}

export function WarehousesPage(){
  const { user }=useAuth(); const [data,setData]=useState({warehouses:[],transfers:[]}); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [mode,setMode]=useState('')
  useEffect(()=>{loadEndpoint('/warehouses/',user.role).then(r=>{setData(r.data);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  async function submit(form){const payload=mode==='warehouse'?{...form,action:'warehouse'}:{...form,action:'transfer'};const r=await createEndpoint('/warehouses/',payload,user.role);setData(c=>mode==='warehouse'?{...c,warehouses:[...c.warehouses,r.item]}:{...c,transfers:[r.item,...c.transfers]})}
  return <><OpsHeader eyebrow="Locations" title="Multi-warehouse stock" copy="See branch capacity and move stock between stores with a traceable transfer reference." action={<div className="inline-actions"><button className="button ghost app-action" onClick={()=>setMode('warehouse')}>+ Warehouse</button><button className="button app-action" onClick={()=>setMode('transfer')}>Transfer stock</button></div>}/>{loading?<Loading/>:error?<ErrorBox message={error}/>:<><div className="warehouse-grid">{data.warehouses.map(w=><article className="supplier-card" key={w.id}><div className="supplier-icon">{w.code.slice(0,2)}</div><h3>{w.name}</h3><p>{w.code}</p><dl><div><dt>SKUs</dt><dd>{w.sku_count}</dd></div><div><dt>Units</dt><dd>{w.units}</dd></div></dl><small>{w.address}</small></article>)}</div><div className="section-gap"><div className="card-title"><div><span className="eyebrow">Movement</span><h2>Recent transfers</h2></div></div><div className="table-card"><table><thead><tr><th>Reference</th><th>From → To</th><th>Part</th><th>Qty</th><th>Status</th></tr></thead><tbody>{data.transfers.map(t=><tr key={t.id}><td><b>{t.reference}</b></td><td>{t.from_warehouse} → {t.to_warehouse}</td><td><b>{t.product}</b><small>{t.sku}</small></td><td>{t.quantity}</td><td className="capitalize">{t.status}</td></tr>)}</tbody></table></div></div></>}{mode==='warehouse'&&<CreateModal title="Add warehouse" copy="Create a branch or store location." submitLabel="Create warehouse" onClose={()=>setMode('')} onSubmit={submit} fields={[{name:'code',label:'Code',required:true},{name:'name',label:'Warehouse name',required:true},{name:'address',label:'Address',span:2}]}/>} {mode==='transfer'&&<CreateModal title="Transfer stock" copy="Move inventory from one branch to another." submitLabel="Transfer" onClose={()=>setMode('')} onSubmit={submit} fields={[{name:'from_warehouse',label:'From code',required:true},{name:'to_warehouse',label:'To code',required:true},{name:'sku',label:'SKU',required:true},{name:'quantity',label:'Quantity',type:'number',required:true,min:'1'}]}/>}</>
}

export function ReorderPage(){
  const { user }=useAuth(); const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [created,setCreated]=useState({})
  useEffect(()=>{loadEndpoint('/reorder/',user.role).then(r=>{setItems(r.data.items);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  async function reorder(x){const r=await createEndpoint('/reorder/',{sku:x.sku,quantity:x.suggested_qty},user.role);setCreated(c=>({...c,[x.sku]:r.item.po_no}))}
  return <><OpsHeader eyebrow="Replenishment" title="Low-stock & reorder desk" copy="Prioritise shortages and create approved purchase orders from recommended quantities."/>{loading?<Loading/>:error?<ErrorBox message={error}/>:items.length===0?<div className="loading-card">No items need replenishment. A rare and beautiful warehouse moment.</div>:<div className="table-card"><table><thead><tr><th>Part</th><th>Supplier</th><th>On hand</th><th>Threshold</th><th>Suggested order</th><th>Exposure</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.name}</b><small>{x.sku}</small></td><td>{x.supplier||'Unassigned'}</td><td><b>{x.stock_qty}</b></td><td>{x.reorder_level}</td><td>{x.suggested_qty}</td><td>₹{(x.suggested_qty*x.unit_price).toLocaleString('en-IN')}</td><td>{created[x.sku]?<small>{created[x.sku]}</small>:<button className="mini-button" onClick={()=>reorder(x)}>Create PO</button>}</td></tr>)}</tbody></table></div>}</>
}

export function SalesFlowPage(){
  const { user }=useAuth(); const [data,setData]=useState({orders:[],invoices:[]}); const [quotes,setQuotes]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  useEffect(()=>{Promise.all([loadEndpoint('/sales-flow/',user.role),loadEndpoint('/quotations/',user.role)]).then(([a,b])=>{setData(a.data);setQuotes(b.data.items);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  async function convert(id){const r=await createEndpoint('/sales-flow/',{action:'convert_quote',quote_id:id},user.role);setData(c=>({...c,orders:[r.item,...c.orders.filter(x=>x.id!==r.item.id)]}))}
  async function invoice(id){const r=await createEndpoint('/sales-flow/',{action:'invoice',order_id:id},user.role);setData(c=>({orders:c.orders.map(x=>x.id===id?{...x,invoice_no:r.item.invoice_no}:x),invoices:[r.item,...c.invoices.filter(x=>x.id!==r.item.id)]}))}
  const convertible=quotes.filter(q=>!data.orders.some(o=>o.quote_no===q.quote_no))
  return <><OpsHeader eyebrow="Revenue flow" title="Quote → order → invoice" copy="Move accepted quotations into confirmed orders and issue invoices without re-entering customer totals."/>{loading?<Loading/>:error?<ErrorBox message={error}/>:<><div className="dashboard-grid"><article className="data-card"><div className="card-title"><div><span className="eyebrow">Ready</span><h2>Convertible quotes</h2></div></div><div className="simple-list">{convertible.slice(0,6).map(q=><div className="simple-row" key={q.id}><div><b>{q.customer_company||q.customer_name}</b><small>{q.quote_no} · ₹{Number(q.total).toLocaleString('en-IN')}</small></div><span className="capitalize">{q.status}</span><button className="mini-button" onClick={()=>convert(q.id)}>Create order</button></div>)}</div></article><article className="data-card"><div className="card-title"><div><span className="eyebrow">Billing</span><h2>Open orders</h2></div></div><div className="simple-list">{data.orders.slice(0,6).map(o=><div className="simple-row" key={o.id}><div><b>{o.customer_company||o.customer_name}</b><small>{o.order_no}</small></div><strong>₹{Number(o.total).toLocaleString('en-IN')}</strong>{o.invoice_no?<small>{o.invoice_no}</small>:<button className="mini-button" onClick={()=>invoice(o.id)}>Invoice</button>}</div>)}</div></article></div><div className="section-gap"><div className="card-title"><div><span className="eyebrow">Receivables</span><h2>Invoices</h2></div></div><div className="table-card"><table><thead><tr><th>Invoice</th><th>Order</th><th>Customer</th><th>Total</th><th>Due</th><th>Status</th></tr></thead><tbody>{data.invoices.map(i=><tr key={i.id}><td><b>{i.invoice_no}</b></td><td>{i.order_no}</td><td>{i.customer}</td><td>₹{Number(i.total).toLocaleString('en-IN')}</td><td>{i.due_date}</td><td className="capitalize">{i.status}</td></tr>)}</tbody></table></div></div></>}</>
}

export function CustomersPage(){
  const { user }=useAuth(); const [items,setItems]=useState([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [creating,setCreating]=useState(false)
  useEffect(()=>{loadEndpoint('/customers/',user.role).then(r=>{setItems(r.data.items);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  const filtered=items.filter(x=>!q||[x.name,x.company,x.email,x.phone,x.customer_type].join(' ').toLowerCase().includes(q.toLowerCase()))
  async function add(form){const r=await createEndpoint('/customers/',form,user.role);setItems(c=>[r.item,...c])}
  return <><OpsHeader eyebrow="Relationships" title="Customer & dealer CRM" copy="Keep dealer terms, credit exposure and account context next to sales activity." action={<button className="button app-action" onClick={()=>setCreating(true)}>+ Add customer</button>}/><div className="toolbar"><div className="searchbox">⌕<input placeholder="Search company, contact, dealer type…" value={q} onChange={e=>setQ(e.target.value)}/></div><span>{filtered.length} accounts</span></div>{loading?<Loading/>:error?<ErrorBox message={error}/>:<div className="table-card"><table><thead><tr><th>Account</th><th>Type</th><th>Contact</th><th>Terms</th><th>Credit limit</th><th>Outstanding</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><b>{c.company||c.name}</b><small>{c.name}</small></td><td className="capitalize">{c.customer_type}</td><td>{c.email}<small>{c.phone}</small></td><td>{c.payment_terms_days} days</td><td>₹{Number(c.credit_limit).toLocaleString('en-IN')}</td><td><b>₹{Number(c.outstanding_balance).toLocaleString('en-IN')}</b></td></tr>)}</tbody></table></div>}{creating&&<CreateModal title="Add customer account" copy="Capture the commercial details sales needs before the next quotation." submitLabel="Add customer" onClose={()=>setCreating(false)} onSubmit={add} initial={{customer_type:'retail',payment_terms_days:0,credit_limit:0,outstanding_balance:0}} fields={[{name:'name',label:'Contact name',required:true},{name:'company',label:'Company'},{name:'email',label:'Email',type:'email'},{name:'phone',label:'Phone'},{name:'customer_type',label:'Type',type:'select',options:['retail','dealer','fleet','workshop']},{name:'payment_terms_days',label:'Payment terms (days)',type:'number',min:'0'},{name:'credit_limit',label:'Credit limit',type:'number',min:'0'},{name:'outstanding_balance',label:'Opening outstanding',type:'number',min:'0'},{name:'notes',label:'Notes',span:2}]}/>}</>
}

export function PricingPage(){
  const { user }=useAuth(); const [rules,setRules]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [creating,setCreating]=useState(false); const [previewing,setPreviewing]=useState(false); const [preview,setPreview]=useState(null)
  useEffect(()=>{loadEndpoint('/pricing/',user.role).then(r=>{setRules(r.data.items);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  async function add(form){const r=await createEndpoint('/pricing/',form,user.role);setRules(c=>[...c,r.item])}
  async function calculate(form){const r=await createEndpoint('/pricing/',{...form,action:'preview'},user.role);setPreview(r.item)}
  return <><OpsHeader eyebrow="Commercial engine" title="Pricing & discount rules" copy="Separate retail, dealer and wholesale pricing, then apply quantity rules without calculator gymnastics." action={<div className="inline-actions"><button className="button ghost app-action" onClick={()=>setPreviewing(true)}>Price calculator</button><button className="button app-action" onClick={()=>setCreating(true)}>+ Rule</button></div>}/>{preview&&<article className="pricing-preview"><div><span className="eyebrow">Calculated offer</span><h2>{preview.name}</h2><p>{preview.sku} · {preview.customer_type} · {preview.quantity} units</p></div><div><small>Unit price</small><strong>₹{Number(preview.unit_price).toLocaleString('en-IN')}</strong><span>{preview.discount_percent}% rule discount</span></div><div><small>Line total</small><strong>₹{Number(preview.line_total).toLocaleString('en-IN')}</strong><span>{preview.margin_percent!==null?`${preview.margin_percent}% estimated margin`:'Margin n/a'}</span></div></article>}{loading?<Loading/>:error?<ErrorBox message={error}/>:<div className="table-card"><table><thead><tr><th>Rule</th><th>Customer type</th><th>Minimum qty</th><th>Discount</th><th>Status</th></tr></thead><tbody>{rules.map(r=><tr key={r.id}><td><b>{r.name}</b></td><td className="capitalize">{r.customer_type}</td><td>{r.min_qty}</td><td>{r.discount_percent}%</td><td>{r.active?'Active':'Paused'}</td></tr>)}</tbody></table></div>}{creating&&<CreateModal title="Add price rule" copy="Apply a quantity discount to a customer segment." submitLabel="Add rule" onClose={()=>setCreating(false)} onSubmit={add} initial={{customer_type:'dealer',min_qty:1,discount_percent:0}} fields={[{name:'name',label:'Rule name',required:true,span:2},{name:'customer_type',label:'Customer type',type:'select',options:['retail','dealer','fleet','workshop']},{name:'min_qty',label:'Minimum quantity',type:'number',min:'1'},{name:'discount_percent',label:'Discount %',type:'number',min:'0',step:'0.1'}]}/>} {previewing&&<CreateModal title="Price calculator" copy="Preview the price that a customer segment receives at a given quantity." submitLabel="Calculate" onClose={()=>setPreviewing(false)} onSubmit={calculate} initial={{customer_type:'dealer',quantity:1}} fields={[{name:'sku',label:'SKU',required:true},{name:'customer_type',label:'Customer type',type:'select',options:['retail','dealer','fleet','workshop']},{name:'quantity',label:'Quantity',type:'number',min:'1',required:true}]}/>}</>
}
