import { useEffect, useState } from 'react'
import { createEndpoint, loadEndpoint } from '../api/client'
import { useAuth } from '../context/AuthContext'
import CreateModal from '../components/CreateModal'

function OpsHeader({ eyebrow, title, copy, action }) {
  return <header className="app-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{action}</header>
}
function Loading(){ return <div className="loading-card">Loading operational data…</div> }
function ErrorBox({ message }){ return <div className="error-card">{message}</div> }
export function BarcodePage(){
  const { user }=useAuth(); const [items,setItems]=useState([]); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [creating,setCreating]=useState(false); const [q,setQ]=useState('')
  useEffect(()=>{loadEndpoint('/barcodes/',user.role).then(r=>{setItems(r.data.items);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  const filtered=items.filter(x=>!q || [x.sku,x.name,x.barcode].join(' ').toLowerCase().includes(q.toLowerCase()))
  async function assign(form){const r=await createEndpoint('/barcodes/',form,user.role);setItems(curr=>[r.item,...curr.filter(x=>x.id!==r.item.id)])}
  return <><OpsHeader eyebrow="Scan desk" title="Barcode & QR labels" copy="Assign, scan and search part labels from one fast inventory surface." action={<button className="button app-action" onClick={()=>setCreating(true)}>Assign label</button>}/>
    <div className="toolbar"><div className="searchbox">▣<input autoFocus placeholder="Scan barcode, QR value or enter SKU…" value={q} onChange={e=>setQ(e.target.value)}/></div><span>{filtered.length} labelled parts</span></div>
    {loading?<Loading/>:error?<ErrorBox message={error}/>:<div className="table-card"><table><thead><tr><th>Part</th><th>Barcode / QR value</th><th>Stock</th><th>Bin</th><th>Label</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><b>{x.name}</b><small>{x.sku} · {x.brand}</small></td><td><code>{x.barcode || 'Not assigned'}</code></td><td>{x.stock_qty}</td><td>{x.bin_location}</td><td><button className="mini-button" onClick={()=>window.print()}>Print</button></td></tr>)}</tbody></table></div>}
    {creating&&<CreateModal title="Assign barcode" copy="Use an existing barcode/QR value or leave blank to generate an internal Partora code." submitLabel="Assign" onClose={()=>setCreating(false)} onSubmit={assign} fields={[{name:'sku',label:'SKU',required:true},{name:'barcode',label:'Barcode / QR value',placeholder:'8901234567890',span:2}]}/>}</>
}

export function FitmentsPage(){
  const { user }=useAuth(); const [items,setItems]=useState([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [creating,setCreating]=useState(false)
  useEffect(()=>{loadEndpoint('/fitments/',user.role).then(r=>{setItems(r.data.items);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  const filtered=items.filter(x=>!q||[x.make,x.model,x.variant,x.engine,x.oem_number,x.sku,x.product].join(' ').toLowerCase().includes(q.toLowerCase()))
  async function add(form){const r=await createEndpoint('/fitments/',form,user.role);setItems(c=>[r.item,...c])}
  return <><OpsHeader eyebrow="Compatibility" title="Vehicle & part fitment" copy="Find compatible parts by make, model, year, variant, engine or OEM reference." action={<button className="button app-action" onClick={()=>setCreating(true)}>+ Add fitment</button>}/><div className="toolbar"><div className="searchbox">⌕<input placeholder="Swift 2022, i20 1.2L, OEM number…" value={q} onChange={e=>setQ(e.target.value)}/></div><span>{filtered.length} matches</span></div>{loading?<Loading/>:error?<ErrorBox message={error}/>:<div className="table-card"><table><thead><tr><th>Vehicle</th><th>Years</th><th>Variant / Engine</th><th>Part</th><th>OEM</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><b>{x.make} {x.model}</b></td><td>{x.year_from}–{x.year_to}</td><td>{x.variant}<small>{x.engine}</small></td><td><b>{x.product}</b><small>{x.sku}</small></td><td>{x.oem_number||'—'}</td></tr>)}</tbody></table></div>}{creating&&<CreateModal title="Add vehicle fitment" copy="Map a catalog SKU to vehicle compatibility and OEM references." submitLabel="Add fitment" onClose={()=>setCreating(false)} onSubmit={add} fields={[{name:'sku',label:'SKU',required:true},{name:'make',label:'Make',required:true},{name:'model',label:'Model',required:true},{name:'year_from',label:'From year',type:'number',required:true},{name:'year_to',label:'To year',type:'number'},{name:'variant',label:'Variant'},{name:'engine',label:'Engine'},{name:'oem_number',label:'OEM number'}]}/>}</>
}

export function PurchaseOrdersPage(){
  const { user }=useAuth(); const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [creating,setCreating]=useState(false)
  useEffect(()=>{loadEndpoint('/purchase-orders/',user.role).then(r=>{setItems(r.data.items);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  async function add(form){const r=await createEndpoint('/purchase-orders/',form,user.role);setItems(c=>[r.item,...c])}
  async function receive(id){const r=await createEndpoint('/purchase-orders/',{action:'receive',id},user.role);setItems(c=>c.map(x=>x.id===id?{...x,...r.item}:x))}
  return <><OpsHeader eyebrow="Purchasing" title="Purchase orders" copy="Create supplier orders, track expected delivery and receive stock directly into inventory." action={<button className="button app-action" onClick={()=>setCreating(true)}>+ New PO</button>}/>{loading?<Loading/>:error?<ErrorBox message={error}/>:<div className="table-card"><table><thead><tr><th>PO</th><th>Supplier</th><th>Expected</th><th>Total</th><th>Lines received</th><th>Status</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.po_no}</b><small>{x.created_by}</small></td><td>{x.supplier}</td><td>{x.expected_date||'—'}</td><td>₹{Number(x.total||0).toLocaleString('en-IN')}</td><td>{x.received_lines}/{x.line_count}</td><td className="capitalize">{x.status}</td><td>{x.status!=='received'&&<button className="mini-button" onClick={()=>receive(x.id)}>Receive</button>}</td></tr>)}</tbody></table></div>}{creating&&<CreateModal title="New purchase order" copy="Start with one catalog line; additional line-item editing can be layered on this workflow." submitLabel="Create PO" onClose={()=>setCreating(false)} onSubmit={add} initial={{status:'draft',quantity:1}} fields={[{name:'supplier',label:'Supplier',required:true,placeholder:'TorqueLine Components'},{name:'sku',label:'SKU',required:true},{name:'quantity',label:'Quantity',type:'number',required:true,min:'1'},{name:'unit_cost',label:'Unit cost',type:'number',required:true,min:'0',step:'0.01'},{name:'expected_date',label:'Expected date',type:'date'},{name:'status',label:'Status',type:'select',options:['draft','approved','ordered']}]}/>}</>
}

export function WarehousesPage(){
  const { user }=useAuth(); const [data,setData]=useState({warehouses:[],transfers:[]}); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [mode,setMode]=useState('')
  useEffect(()=>{loadEndpoint('/warehouses/',user.role).then(r=>{setData(r.data);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  async function submit(form){const payload=mode==='warehouse'?{...form,action:'warehouse'}:{...form,action:'transfer'};const r=await createEndpoint('/warehouses/',payload,user.role);setData(c=>mode==='warehouse'?{...c,warehouses:[...c.warehouses,r.item]}:{...c,transfers:[r.item,...c.transfers]})}
  return <><OpsHeader eyebrow="Locations" title="Multi-warehouse stock" copy="See branch capacity and move stock between stores with a traceable transfer reference." action={<div className="inline-actions"><button className="button ghost app-action" onClick={()=>setMode('warehouse')}>+ Warehouse</button><button className="button app-action" onClick={()=>setMode('transfer')}>Transfer stock</button></div>}/>{loading?<Loading/>:error?<ErrorBox message={error}/>:<><div className="warehouse-grid">{data.warehouses.map(w=><article className="supplier-card" key={w.id}><div className="supplier-icon">{w.code.slice(0,2)}</div><h3>{w.name}</h3><p>{w.code}</p><dl><div><dt>SKUs</dt><dd>{w.sku_count}</dd></div><div><dt>Units</dt><dd>{w.units}</dd></div></dl><small>{w.address}</small></article>)}</div><div className="section-gap"><div className="card-title"><div><span className="eyebrow">Movement</span><h2>Recent transfers</h2></div></div><div className="table-card"><table><thead><tr><th>Reference</th><th>From → To</th><th>Part</th><th>Qty</th><th>Status</th></tr></thead><tbody>{data.transfers.map(t=><tr key={t.id}><td><b>{t.reference}</b></td><td>{t.from_warehouse} → {t.to_warehouse}</td><td><b>{t.product}</b><small>{t.sku}</small></td><td>{t.quantity}</td><td className="capitalize">{t.status}</td></tr>)}</tbody></table></div></div></>}{mode==='warehouse'&&<CreateModal title="Add warehouse" copy="Create a branch or store location." submitLabel="Create warehouse" onClose={()=>setMode('')} onSubmit={submit} fields={[{name:'code',label:'Code',required:true},{name:'name',label:'Warehouse name',required:true},{name:'address',label:'Address',span:2}]}/>} {mode==='transfer'&&<CreateModal title="Transfer stock" copy="Move inventory from one branch to another." submitLabel="Transfer" onClose={()=>setMode('')} onSubmit={submit} fields={[{name:'from_warehouse',label:'From code',required:true},{name:'to_warehouse',label:'To code',required:true},{name:'sku',label:'SKU',required:true},{name:'quantity',label:'Quantity',type:'number',required:true,min:'1'}]}/>}</>
}

export function ReorderPage(){
  const { user }=useAuth(); const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [created,setCreated]=useState({})
  useEffect(()=>{loadEndpoint('/reorder/',user.role).then(r=>{setItems(r.data.items);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  async function reorder(x){const r=await createEndpoint('/reorder/',{sku:x.sku,quantity:x.suggested_qty},user.role);setCreated(c=>({...c,[x.sku]:r.item.po_no}))}
  return <><OpsHeader eyebrow="Replenishment" title="Low-stock & reorder desk" copy="Prioritise shortages and create approved purchase orders from recommended quantities."/>{loading?<Loading/>:error?<ErrorBox message={error}/>:items.length===0?<div className="loading-card">No items need replenishment. A rare and beautiful warehouse moment.</div>:<div className="table-card"><table><thead><tr><th>Part</th><th>Supplier</th><th>On hand</th><th>Threshold</th><th>Suggested order</th><th>Exposure</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.name}</b><small>{x.sku}</small></td><td>{x.supplier||'Unassigned'}</td><td><b>{x.stock_qty}</b></td><td>{x.reorder_level}</td><td>{x.suggested_qty}</td><td>₹{(x.suggested_qty*x.unit_price).toLocaleString('en-IN')}</td><td>{created[x.sku]?<small>{created[x.sku]}</small>:<button className="mini-button" onClick={()=>reorder(x)}>Create PO</button>}</td></tr>)}</tbody></table></div>}</>
}

export function SalesFlowPage(){
  const { user }=useAuth(); const [data,setData]=useState({orders:[],invoices:[]}); const [quotes,setQuotes]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  useEffect(()=>{Promise.all([loadEndpoint('/sales-flow/',user.role),loadEndpoint('/quotations/',user.role)]).then(([a,b])=>{setData(a.data);setQuotes(b.data.items);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  async function convert(id){const r=await createEndpoint('/sales-flow/',{action:'convert_quote',quote_id:id},user.role);setData(c=>({...c,orders:[r.item,...c.orders.filter(x=>x.id!==r.item.id)]}))}
  async function invoice(id){const r=await createEndpoint('/sales-flow/',{action:'invoice',order_id:id},user.role);setData(c=>({orders:c.orders.map(x=>x.id===id?{...x,invoice_no:r.item.invoice_no}:x),invoices:[r.item,...c.invoices.filter(x=>x.id!==r.item.id)]}))}
  const convertible=quotes.filter(q=>!data.orders.some(o=>o.quote_no===q.quote_no))
  return <><OpsHeader eyebrow="Revenue flow" title="Quote → order → invoice" copy="Move accepted quotations into confirmed orders and issue invoices without re-entering customer totals."/>{loading?<Loading/>:error?<ErrorBox message={error}/>:<><div className="dashboard-grid"><article className="data-card"><div className="card-title"><div><span className="eyebrow">Ready</span><h2>Convertible quotes</h2></div></div><div className="simple-list">{convertible.slice(0,6).map(q=><div className="simple-row" key={q.id}><div><b>{q.customer_company||q.customer_name}</b><small>{q.quote_no} · ₹{Number(q.total).toLocaleString('en-IN')}</small></div><span className="capitalize">{q.status}</span><button className="mini-button" onClick={()=>convert(q.id)}>Create order</button></div>)}</div></article><article className="data-card"><div className="card-title"><div><span className="eyebrow">Billing</span><h2>Open orders</h2></div></div><div className="simple-list">{data.orders.slice(0,6).map(o=><div className="simple-row" key={o.id}><div><b>{o.customer_company||o.customer_name}</b><small>{o.order_no}</small></div><strong>₹{Number(o.total).toLocaleString('en-IN')}</strong>{o.invoice_no?<small>{o.invoice_no}</small>:<button className="mini-button" onClick={()=>invoice(o.id)}>Invoice</button>}</div>)}</div></article></div><div className="section-gap"><div className="card-title"><div><span className="eyebrow">Receivables</span><h2>Invoices</h2></div></div><div className="table-card"><table><thead><tr><th>Invoice</th><th>Order</th><th>Customer</th><th>Total</th><th>Due</th><th>Status</th></tr></thead><tbody>{data.invoices.map(i=><tr key={i.id}><td><b>{i.invoice_no}</b></td><td>{i.order_no}</td><td>{i.customer}</td><td>₹{Number(i.total).toLocaleString('en-IN')}</td><td>{i.due_date}</td><td className="capitalize">{i.status}</td></tr>)}</tbody></table></div></div></>}</>
}

export function CustomersPage(){
  const { user }=useAuth(); const [items,setItems]=useState([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [creating,setCreating]=useState(false)
  useEffect(()=>{loadEndpoint('/customers/',user.role).then(r=>{setItems(r.data.items);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  const filtered=items.filter(x=>!q||[x.name,x.company,x.email,x.phone,x.customer_type].join(' ').toLowerCase().includes(q.toLowerCase()))
  async function add(form){const r=await createEndpoint('/customers/',form,user.role);setItems(c=>[r.item,...c])}
  return <><OpsHeader eyebrow="Relationships" title="Customer & dealer CRM" copy="Keep dealer terms, credit exposure and account context next to sales activity." action={<button className="button app-action" onClick={()=>setCreating(true)}>+ Add customer</button>}/><div className="toolbar"><div className="searchbox">⌕<input placeholder="Search company, contact, dealer type…" value={q} onChange={e=>setQ(e.target.value)}/></div><span>{filtered.length} accounts</span></div>{loading?<Loading/>:error?<ErrorBox message={error}/>:<div className="table-card"><table><thead><tr><th>Account</th><th>Type</th><th>Contact</th><th>Terms</th><th>Credit limit</th><th>Outstanding</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><b>{c.company||c.name}</b><small>{c.name}</small></td><td className="capitalize">{c.customer_type}</td><td>{c.email}<small>{c.phone}</small></td><td>{c.payment_terms_days} days</td><td>₹{Number(c.credit_limit).toLocaleString('en-IN')}</td><td><b>₹{Number(c.outstanding_balance).toLocaleString('en-IN')}</b></td></tr>)}</tbody></table></div>}{creating&&<CreateModal title="Add customer account" copy="Capture the commercial details sales needs before the next quotation." submitLabel="Add customer" onClose={()=>setCreating(false)} onSubmit={add} initial={{customer_type:'retail',payment_terms_days:0,credit_limit:0,outstanding_balance:0}} fields={[{name:'name',label:'Contact name',required:true},{name:'company',label:'Company'},{name:'email',label:'Email',type:'email'},{name:'phone',label:'Phone'},{name:'customer_type',label:'Type',type:'select',options:['retail','dealer','fleet','workshop']},{name:'payment_terms_days',label:'Payment terms (days)',type:'number',min:'0'},{name:'credit_limit',label:'Credit limit',type:'number',min:'0'},{name:'outstanding_balance',label:'Opening outstanding',type:'number',min:'0'},{name:'notes',label:'Notes',span:2}]}/>}</>
}

export function PricingPage(){
  const { user }=useAuth(); const [rules,setRules]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [creating,setCreating]=useState(false); const [previewing,setPreviewing]=useState(false); const [preview,setPreview]=useState(null)
  useEffect(()=>{loadEndpoint('/pricing/',user.role).then(r=>{setRules(r.data.items);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  async function add(form){const r=await createEndpoint('/pricing/',form,user.role);setRules(c=>[...c,r.item])}
  async function calculate(form){const r=await createEndpoint('/pricing/',{...form,action:'preview'},user.role);setPreview(r.item)}
  return <><OpsHeader eyebrow="Commercial engine" title="Pricing & discount rules" copy="Separate retail, dealer and wholesale pricing, then apply quantity rules without calculator gymnastics." action={<div className="inline-actions"><button className="button ghost app-action" onClick={()=>setPreviewing(true)}>Price calculator</button><button className="button app-action" onClick={()=>setCreating(true)}>+ Rule</button></div>}/>{preview&&<article className="pricing-preview"><div><span className="eyebrow">Calculated offer</span><h2>{preview.name}</h2><p>{preview.sku} · {preview.customer_type} · {preview.quantity} units</p></div><div><small>Unit price</small><strong>₹{Number(preview.unit_price).toLocaleString('en-IN')}</strong><span>{preview.discount_percent}% rule discount</span></div><div><small>Line total</small><strong>₹{Number(preview.line_total).toLocaleString('en-IN')}</strong><span>{preview.margin_percent!==null?`${preview.margin_percent}% estimated margin`:'Margin n/a'}</span></div></article>}{loading?<Loading/>:error?<ErrorBox message={error}/>:<div className="table-card"><table><thead><tr><th>Rule</th><th>Customer type</th><th>Minimum qty</th><th>Discount</th><th>Status</th></tr></thead><tbody>{rules.map(r=><tr key={r.id}><td><b>{r.name}</b></td><td className="capitalize">{r.customer_type}</td><td>{r.min_qty}</td><td>{r.discount_percent}%</td><td>{r.active?'Active':'Paused'}</td></tr>)}</tbody></table></div>}{creating&&<CreateModal title="Add price rule" copy="Apply a quantity discount to a customer segment." submitLabel="Add rule" onClose={()=>setCreating(false)} onSubmit={add} initial={{customer_type:'dealer',min_qty:1,discount_percent:0}} fields={[{name:'name',label:'Rule name',required:true,span:2},{name:'customer_type',label:'Customer type',type:'select',options:['retail','dealer','fleet','workshop']},{name:'min_qty',label:'Minimum quantity',type:'number',min:'1'},{name:'discount_percent',label:'Discount %',type:'number',min:'0',step:'0.1'}]}/>} {previewing&&<CreateModal title="Price calculator" copy="Preview the price that a customer segment receives at a given quantity." submitLabel="Calculate" onClose={()=>setPreviewing(false)} onSubmit={calculate} initial={{customer_type:'dealer',quantity:1}} fields={[{name:'sku',label:'SKU',required:true},{name:'customer_type',label:'Customer type',type:'select',options:['retail','dealer','fleet','workshop']},{name:'quantity',label:'Quantity',type:'number',min:'1',required:true}]}/>}</>
}

function currency(v){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v||0)}
function Bars({items}){const max=Math.max(1,...items.map(x=>Number(x.value)||0));return <div className="bar-list">{items.map(x=><div className="bar-row" key={x.label}><div><b>{x.label}</b><span>{Number(x.value).toLocaleString('en-IN')}</span></div><i><em style={{width:`${Math.max(4,(Number(x.value)||0)/max*100)}%`}}></em></i></div>)}</div>}
export function AnalyticsPage(){
  const { user }=useAuth(); const [data,setData]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  useEffect(()=>{loadEndpoint('/analytics/',user.role).then(r=>{setData(r.data);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  function exportCsv(){if(!data)return;const rows=[['Metric','Value'],...Object.entries(data.metrics)];const blob=new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='partora-analytics.csv';a.click();URL.revokeObjectURL(a.href)}
  return <><OpsHeader eyebrow="Intelligence" title="Analytics & business reports" copy="Track commercial performance, inventory value, conversion and working-capital exposure." action={<button className="button app-action" onClick={exportCsv}>Export CSV</button>}/>{loading?<Loading/>:error?<ErrorBox message={error}/>:<><section className="metric-grid dashboard-metrics"><article><small>Sales orders</small><strong>{currency(data.metrics.sales_total)}</strong><span>confirmed value</span></article><article><small>Inventory value</small><strong>{currency(data.metrics.inventory_value)}</strong><span>{data.metrics.low_stock} low-stock SKUs</span></article><article><small>Outstanding</small><strong>{currency(data.metrics.outstanding)}</strong><span>customer balance</span></article><article><small>Quote conversion</small><strong>{data.metrics.quote_conversion}%</strong><span>approved quotes</span></article></section><section className="analytics-grid"><article className="data-card"><div className="card-title"><div><span className="eyebrow">Mix</span><h2>Catalog categories</h2></div></div><Bars items={data.categories}/></article><article className="data-card"><div className="card-title"><div><span className="eyebrow">Sourcing</span><h2>Supplier SKU coverage</h2></div></div><Bars items={data.suppliers}/></article><article className="data-card"><div className="card-title"><div><span className="eyebrow">Credit</span><h2>Customer exposure</h2></div></div><Bars items={data.top_customers}/></article><article className="data-card insight-card"><span className="eyebrow">Estimated inventory margin</span><strong>{currency(data.metrics.estimated_inventory_margin)}</strong><p>Difference between current catalog selling value and stored product cost across on-hand inventory.</p></article></section></>}</>
}

export function GovernancePage(){
  const { user }=useAuth(); const [data,setData]=useState({notifications:[],approvals:[],audits:[]}); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [creating,setCreating]=useState(false); const canReview=['admin','manager'].includes(user.role)
  useEffect(()=>{loadEndpoint('/governance/',user.role).then(r=>{setData(r.data);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  async function requestApproval(form){const r=await createEndpoint('/governance/',{...form,action:'request'},user.role);setData(c=>({...c,approvals:[r.item,...c.approvals]}))}
  async function review(id,action){const r=await createEndpoint('/governance/',{id,action},user.role);setData(c=>({...c,approvals:c.approvals.map(x=>x.id===id?r.item:x)}))}
  return <><OpsHeader eyebrow="Control" title="Notifications, approvals & audit" copy="Keep exceptional actions reviewable and preserve who changed what across critical workflows." action={<button className="button app-action" onClick={()=>setCreating(true)}>Request approval</button>}/>{loading?<Loading/>:error?<ErrorBox message={error}/>:<><section className="dashboard-grid"><article className="data-card"><div className="card-title"><div><span className="eyebrow">Inbox</span><h2>Notifications</h2></div></div><div className="simple-list">{data.notifications.map(n=><div className="notice-row" key={n.id}><span className={n.read?'notice-dot read':'notice-dot'}></span><div><b>{n.title}</b><small>{n.message}</small></div></div>)}</div></article><article className="data-card"><div className="card-title"><div><span className="eyebrow">Review</span><h2>Approvals</h2></div></div><div className="simple-list">{data.approvals.map(a=><div className="approval-row" key={a.id}><div><b>{a.reference}</b><small>{a.kind} · {a.requested_by} · ₹{Number(a.amount).toLocaleString('en-IN')}</small></div><span className={`status ${a.status==='approved'?'healthy':a.status==='rejected'?'out':'low'}`}>{a.status}</span>{canReview&&a.status==='pending'&&<div><button className="mini-button" onClick={()=>review(a.id,'approve')}>Approve</button> <button className="mini-button" onClick={()=>review(a.id,'reject')}>Reject</button></div>}</div>)}</div></article></section><div className="section-gap"><div className="card-title"><div><span className="eyebrow">Trace</span><h2>Audit history</h2></div></div><div className="table-card"><table><thead><tr><th>User</th><th>Action</th><th>Entity</th><th>Detail</th><th>Time</th></tr></thead><tbody>{data.audits.map(a=><tr key={a.id}><td><b>{a.user}</b></td><td>{a.action}</td><td>{a.entity} {a.entity_id}</td><td>{a.detail}</td><td>{new Date(a.created_at).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</td></tr>)}</tbody></table></div></div></>}{creating&&<CreateModal title="Request approval" copy="Route an exceptional purchase, discount or stock adjustment for review." submitLabel="Submit request" onClose={()=>setCreating(false)} onSubmit={requestApproval} initial={{kind:'purchase',amount:0}} fields={[{name:'kind',label:'Approval type',type:'select',options:['purchase','discount','stock']},{name:'reference',label:'Reference',required:true},{name:'amount',label:'Amount / exposure',type:'number',min:'0'},{name:'notes',label:'Reason',span:2}]}/>}</>
}

export function FulfillmentPage(){
  const { user }=useAuth(); const [data,setData]=useState({orders:[],invoices:[]}); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [paying,setPaying]=useState(null)
  useEffect(()=>{loadEndpoint('/fulfillment/',user.role).then(r=>{setData(r.data);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  function updateOrder(item){setData(c=>({...c,orders:c.orders.map(x=>x.id===item.id?item:x)}))}
  async function reserve(order){const r=await createEndpoint('/fulfillment/',{action:'reserve',order_id:order.id},user.role);updateOrder(r.item)}
  async function move(order,status){const r=await createEndpoint('/fulfillment/',{action:'status',order_id:order.id,status},user.role);updateOrder(r.item)}
  async function issueInvoice(order){const r=await createEndpoint('/sales-flow/',{action:'invoice',order_id:order.id},user.role);setData(c=>({...c,invoices:[r.item,...c.invoices.filter(x=>x.id!==r.item.id)],orders:c.orders.map(x=>x.id===order.id?{...x,invoice_no:r.item.invoice_no}:x)}))}
  async function payment(form){const r=await createEndpoint('/fulfillment/',{action:'payment',order_id:paying.id,...form},user.role);updateOrder(r.item);setData(c=>({...c,invoices:[r.invoice,...c.invoices.filter(x=>x.id!==r.invoice.id)]}));setPaying(null)}
  const next={confirmed:'picking',picking:'packed',packed:'dispatched',dispatched:'delivered'}
  return <><OpsHeader eyebrow="Warehouse to cash" title="Order fulfillment & payments" copy="Reserve stock, move orders through dispatch and keep invoice balances current."/>{loading?<Loading/>:error?<ErrorBox message={error}/>:<><div className="table-card"><table><thead><tr><th>Order</th><th>Customer</th><th>Lines</th><th>Total</th><th>Fulfillment</th><th>Invoice</th><th>Actions</th></tr></thead><tbody>{data.orders.map(o=><tr key={o.id}><td><b>{o.order_no}</b><small>{o.quote_no||'Direct order'}</small></td><td>{o.customer_company||o.customer_name}<small>{o.shipping_address||'Address not set'}</small></td><td>{o.items?.map(i=><small key={i.id}>{i.sku} × {i.quantity}</small>)}</td><td><b>₹{Number(o.total).toLocaleString('en-IN')}</b></td><td><StatusBadge value={o.fulfillment_status||o.status}/></td><td>{o.invoice_no?<small>{o.invoice_no}</small>:<button className="mini-button" onClick={()=>issueInvoice(o)}>Issue invoice</button>}</td><td><div className="inline-actions">{(o.fulfillment_status==='confirmed'||!o.fulfillment_status)&&<button className="mini-button" onClick={()=>reserve(o)}>Reserve</button>}{next[o.fulfillment_status||o.status]&&<button className="mini-button" onClick={()=>move(o,next[o.fulfillment_status||o.status])}>{next[o.fulfillment_status||o.status]}</button>}{o.invoice_no&&<button className="mini-button" onClick={()=>setPaying(o)}>Payment</button>}</div></td></tr>)}</tbody></table></div><div className="section-gap"><div className="card-title"><div><span className="eyebrow">Receivables</span><h2>Payment ledger</h2></div></div><div className="table-card"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>{data.invoices.map(i=><tr key={i.id}><td><b>{i.invoice_no}</b></td><td>{i.customer}</td><td>₹{Number(i.total).toLocaleString('en-IN')}</td><td>₹{Number(i.paid||0).toLocaleString('en-IN')}</td><td><b>₹{Number(i.balance??(i.total-(i.paid||0))).toLocaleString('en-IN')}</b></td><td><StatusBadge value={i.status}/></td></tr>)}</tbody></table></div></div></>}{paying&&<CreateModal title={`Record payment · ${paying.order_no}`} copy="Apply a full or partial payment to the order invoice." submitLabel="Record payment" onClose={()=>setPaying(null)} onSubmit={payment} initial={{amount:paying.total,method:'bank'}} fields={[{name:'amount',label:'Amount',type:'number',required:true,min:'1',step:'0.01'},{name:'method',label:'Method',type:'select',options:[{value:'bank',label:'Bank transfer'},{value:'upi',label:'UPI'},{value:'cash',label:'Cash'},{value:'card',label:'Card'}]},{name:'reference',label:'Reference'}]}/>}</>
}

export function ReturnsPage(){
  const { user }=useAuth(); const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [creating,setCreating]=useState(false)
  useEffect(()=>{loadEndpoint('/returns/',user.role).then(r=>{setItems(r.data.items);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[user.role])
  async function add(form){const r=await createEndpoint('/returns/',{action:'create',...form},user.role);setItems(c=>[r.item,...c]);setCreating(false)}
  async function update(item,status,resolution=''){const r=await createEndpoint('/returns/',{action:'status',id:item.id,status,resolution},user.role);setItems(c=>c.map(x=>x.id===item.id?r.item:x))}
  return <><OpsHeader eyebrow="After-sales" title="Returns, warranty & RMA" copy="Register returned parts, inspect the reason and resolve with refund, replacement, credit or restock." action={<button className="button app-action" onClick={()=>setCreating(true)}>+ New RMA</button>}/>{loading?<Loading/>:error?<ErrorBox message={error}/>:<div className="table-card"><table><thead><tr><th>RMA</th><th>Part</th><th>Customer</th><th>Reason</th><th>Warranty</th><th>Status</th><th>Resolution</th><th>Actions</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.return_no}</b><small>{x.order_no||'No order linked'}</small></td><td><b>{x.product}</b><small>{x.sku} × {x.quantity}</small></td><td>{x.customer_name}</td><td>{x.reason}</td><td>{x.warranty_expires||'—'}</td><td><StatusBadge value={x.status}/></td><td>{x.resolution||'Pending inspection'}</td><td><div className="inline-actions">{x.status==='requested'&&<button className="mini-button" onClick={()=>update(x,'approved')}>Approve</button>}{x.status==='approved'&&<button className="mini-button" onClick={()=>update(x,'received')}>Received</button>}{x.status==='received'&&<button className="mini-button" onClick={()=>update(x,'inspected')}>Inspect</button>}{x.status==='inspected'&&<><button className="mini-button" onClick={()=>update(x,'resolved','restock')}>Restock</button><button className="mini-button" onClick={()=>update(x,'resolved','refund')}>Refund</button></>}{x.status==='resolved'&&<small>{x.stock_restocked?'Stock returned':'Closed'}</small>}</div></td></tr>)}</tbody></table></div>}{creating&&<CreateModal title="Create return request" copy="Capture the part, customer issue and warranty context for inspection." submitLabel="Create RMA" onClose={()=>setCreating(false)} onSubmit={add} initial={{quantity:1}} fields={[{name:'sku',label:'SKU',required:true},{name:'customer_name',label:'Customer',required:true},{name:'order_no',label:'Order number'},{name:'quantity',label:'Quantity',type:'number',min:'1',required:true},{name:'warranty_expires',label:'Warranty expires',type:'date'},{name:'refund_amount',label:'Refund amount',type:'number',min:'0',step:'0.01'},{name:'reason',label:'Return reason',required:true,span:2}]}/>}</>
}
